import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faUser,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faSearch,
  faChartBar,
  faWallet,
  faCreditCard,
  faHome,
  faCar,
  faUtensils,
  faBus,
  faFileInvoice,
  faPlus,
  faMinus,
  faArrowUp,
  faArrowDown,
  faCheck,
  faTimes,
  faBell,
  faCog,
  faSignOutAlt,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faMicrophone,
  faGraduationCap,
  faLightbulb,
  faBriefcase,
  faBuilding,
  faCloud,
  faWifi,
  faDesktop,
  faCircle,
  faSquare,
  faBullseye,
  faShieldAlt,
  faQuestionCircle,
  faInfoCircle,
  faGamepad,
  faMusic,
  faFilm,
  faBook,
  faShoppingCart,
  faGift,
  faTv,
  faPlane,
  faHeart,
  faCoins,
  faDollarSign,
  faStar,
  faFire,
  faDumbbell,
  faCoffee,
  faPizzaSlice,
  faGasPump,
  faParking,
  faTrain,
  faSubway,
  faBicycle,
  faMotorcycle,
  faShoppingBag,
  faTshirt,
  faCut,
  faPaw,
  faBaby,
  faPills,
  faStethoscope,
  faToiletPaper,
  faCouch,
  faTools,
  faLaptop,
  faMobileAlt,
  faHeadphones,
  faCamera,
  faNewspaper,
  faMoneyBillWave,
  faPiggyBank,
  faUniversity,
  faReceipt,
  faHandHoldingUsd,
  faChartLine,
  faChartPie,
  faCalendarAlt,
  faTag,
  faTags,
  faPercent,
  faExclamationTriangle,
  faCheckCircle,
  faRedo,
  faEdit,
  faTrash,
  faDownload,
  faFileExport,
  faFilePdf,
  faHistory,
  faFilter,
  faSort,
  faTrophy,
  faUsers,
  faMedal,
  faFish,
  faRibbon,
  faHatWizard,
  faGlasses,
  faGem,
  faCrown,
  faCapsules,
  faBed,
  faSeedling,
  faPaperPlane,
  faMapMarkerAlt,
  faMap,
  faGlobe,
} from '@fortawesome/free-solid-svg-icons';
import {
  faBell as faBellOutline,
  faUser as faUserOutline,
  faCircle as faCircleOutline,
} from '@fortawesome/free-regular-svg-icons';
import {
  faSpotify,
  faYoutube,
  faAmazon,
  faApple,
  faGoogle,
  faDiscord,
  faTwitch,
  faPlaystation,
  faXbox,
  faSteam,
  faDropbox,
  faSlack,
} from '@fortawesome/free-brands-svg-icons';
import { colors } from '../theme';

const faNetflix = faFilm;


export const icons = {
  // Solid icons
  user: faUser,
  userOutline: faUserOutline,
  envelope: faEnvelope,
  lock: faLock,
  eye: faEye,
  eyeSlash: faEyeSlash,
  search: faSearch,
  chartBar: faChartBar,
  chartLine: faChartLine,
  chartPie: faChartPie,
  wallet: faWallet,
  creditCard: faCreditCard,
  home: faHome,
  car: faCar,
  utensils: faUtensils,
  bus: faBus,
  train: faTrain,
  subway: faSubway,
  bicycle: faBicycle,
  motorcycle: faMotorcycle,
  plane: faPlane,
  fileInvoice: faFileInvoice,
  plus: faPlus,
  minus: faMinus,
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  check: faCheck,
  checkCircle: faCheckCircle,
  times: faTimes,
  bell: faBell,
  bellOutline: faBellOutline,
  cog: faCog,
  signOut: faSignOutAlt,
  chevronRight: faChevronRight,
  chevronLeft: faChevronLeft,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  close: faTimes,
  microphone: faMicrophone,
  graduationCap: faGraduationCap,
  lightbulb: faLightbulb,
  briefcase: faBriefcase,
  building: faBuilding,
  cloud: faCloud,
  wifi: faWifi,
  desktop: faDesktop,
  laptop: faLaptop,
  mobile: faMobileAlt,
  headphones: faHeadphones,
  camera: faCamera,
  circle: faCircle,
  circleOutline: faCircleOutline,
  square: faSquare,
  bullseye: faBullseye,
  shield: faShieldAlt,
  question: faQuestionCircle,
  info: faInfoCircle,
  exclamation: faExclamationTriangle,
  
  // Entertainment & Subscriptions
  gamepad: faGamepad,
  music: faMusic,
  film: faFilm,
  tv: faTv,
  book: faBook,
  newspaper: faNewspaper,
  
  // Shopping
  shoppingCart: faShoppingCart,
  shoppingBag: faShoppingBag,
  gift: faGift,
  tshirt: faTshirt,
  
  // Health & Personal
  heart: faHeart,
  heartOutline: faHeart,
  coins: faCoins,
  dollarSign: faDollarSign,
  star: faStar,
  fire: faFire,
  dumbbell: faDumbbell,
  pills: faPills,
  stethoscope: faStethoscope,
  cut: faCut,
  paw: faPaw,
  baby: faBaby,
  toiletPaper: faToiletPaper,
  
  // Food & Drink
  coffee: faCoffee,
  pizza: faPizzaSlice,
  
  // Transport
  gasPump: faGasPump,
  parking: faParking,
  
  // Home
  couch: faCouch,
  tools: faTools,
  
  // Finance
  moneyBill: faMoneyBillWave,
  moneyBillWave: faMoneyBillWave,
  piggyBank: faPiggyBank,
  bank: faUniversity,
  university: faUniversity,
  receipt: faReceipt,
  handMoney: faHandHoldingUsd,
  
  // Organization
  calendar: faCalendarAlt,
  tag: faTag,
  tags: faTags,
  percent: faPercent,
  
  // Actions
  repeat: faRedo,
  refresh: faRedo,
  edit: faEdit,
  trash: faTrash,
  download: faDownload,
  fileExport: faFileExport,
  filePdf: faFilePdf,
  history: faHistory,
  filter: faFilter,
  sort: faSort,
  trophy: faTrophy,
  users: faUsers,
  medal: faMedal,
  fish: faFish,
  ribbon: faRibbon,
  hatWizard: faHatWizard,
  glasses: faGlasses,
  gem: faGem,
  crown: faCrown,
  capsules: faCapsules,
  bed: faBed,
  seedling: faSeedling,
  paperPlane: faPaperPlane,
  mapMarkerAlt: faMapMarkerAlt,
  map: faMap,
  globe: faGlobe,
  
  // Brand icons (subscriptions)
  netflix: faNetflix,
  spotify: faSpotify,
  youtube: faYoutube,
  amazon: faAmazon,
  apple: faApple,
  google: faGoogle,
  discord: faDiscord,
  twitch: faTwitch,
  playstation: faPlaystation,
  xbox: faXbox,
  steam: faSteam,
  dropbox: faDropbox,
  slack: faSlack,
} as const;

export type IconName = keyof typeof icons;

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
}

export const Icon: React.FC<IconProps> = ({
  name,
  size = 20,
  color = colors.onSurface,
}) => {
  return (
    <FontAwesomeIcon
      icon={icons[name]}
      size={size}
      color={color}
    />
  );
};

// Popular subscription services with their icons
export const subscriptionIcons: Record<string, IconName> = {
  'Netflix': 'netflix',
  'Spotify': 'spotify',
  'YouTube': 'youtube',
  'YouTube Premium': 'youtube',
  'Amazon Prime': 'amazon',
  'Apple Music': 'apple',
  'Apple TV+': 'apple',
  'iCloud': 'apple',
  'Google One': 'google',
  'Discord Nitro': 'discord',
  'Twitch': 'twitch',
  'PlayStation Plus': 'playstation',
  'Xbox Game Pass': 'xbox',
  'Steam': 'steam',
  'Dropbox': 'dropbox',
  'Slack': 'slack',
};

// Category icons
export const categoryIcons: Record<string, IconName> = {
  'Konut': 'home',
  'Kira': 'home',
  'Ulaşım': 'car',
  'Yemek': 'utensils',
  'Market': 'shoppingCart',
  'Fatura': 'fileInvoice',
  'Elektrik': 'lightbulb',
  'Su': 'home',
  'Doğalgaz': 'gasPump',
  'İnternet': 'wifi',
  'Telefon': 'mobile',
  'Eğlence': 'gamepad',
  'Sağlık': 'stethoscope',
  'Eğitim': 'graduationCap',
  'Giyim': 'tshirt',
  'Spor': 'dumbbell',
  'Güzellik': 'cut',
  'Evcil Hayvan': 'paw',
  'Bebek': 'baby',
  'Sigorta': 'shield',
  'Kredi': 'bank',
  'Tasarruf': 'piggyBank',
  'Yatırım': 'chartLine',
  'Maaş': 'moneyBill',
  'Gelir': 'arrowUp',
  'Gider': 'arrowDown',
};
